entre V1 et V2, on apronfondit les headers de image calculator de SPM et la fct nibabel, plus le type du bit map 

#  FLI-IAM    Comparaison entre gold star (pure batch SPM) et le presque même batch (en nipype)


In [11]:
import numpy as np     
import nibabel as nib     
import os 

## 1 - Segment

In [4]:
!diff  /scratch/user/hirsch/goldstd/data_set/t0009/repos01/T1/c1t0009_t1_s03.nii   /scratch/user/hirsch/datadir/data_results_py/structural/native_class/c1t0009_t1_s03.nii

In [5]:
!diff  /scratch/user/hirsch/goldstd/data_set/t0009/repos01/T1/c2t0009_t1_s03.nii   /scratch/user/hirsch/datadir/data_results_py/structural/native_class/c2t0009_t1_s03.nii

La segmentation est la même au bit près

## 2 -  Image calculator

In [6]:
!diff     /scratch/user/hirsch/goldstd/data_set/t0009/repos01/T1/dmt0009_t1_s02.nii  /scratch/user/hirsch/datadir/data_results_py/structural/t1_masked_files/struct_image.nii

Les fichiers binaires /scratch/user/hirsch/goldstd/data_set/t0009/repos01/T1/dmt0009_t1_s02.nii et /scratch/user/hirsch/datadir/data_results_py/structural/t1_masked_files/struct_image.nii sont différents


In [7]:
# le header de la sortie de image calculator
!fslhd /scratch/user/hirsch/goldstd/data_set/t0009/repos01/T1/dmt0009_t1_s02.nii

filename       /scratch/user/hirsch/goldstd/data_set/t0009/repos01/T1/dmt0009_t1_s02.nii

sizeof_hdr     348
data_type      INT16
dim0           3
dim1           180
dim2           256
dim3           256
dim4           1
dim5           1
dim6           1
dim7           1
vox_units      mm
time_units     s
datatype       4
nbyper         2
bitpix         16
pixdim0        0.000000
pixdim1        1.000000
pixdim2        1.000000
pixdim3        1.000000
pixdim4        0.000000
pixdim5        0.000000
pixdim6        0.000000
pixdim7        0.000000
vox_offset     352
cal_max        0.0000
cal_min        0.0000
scl_slope      0.044728
scl_inter      0.000000
phase_dim      0
freq_dim       0
slice_dim      0
slice_name     Unknown
slice_code     0
slice_start    0
slice_end      0
slice_duration 0.000000
time_offset    0.000000
intent         Unknown
intent_code    0
intent_name    
intent_p1      0.000000
intent_p2      0.000000
intent_p3      0.000000
qform_name     Aligned Anat
qform_cod

comparaison des headers

In [20]:
%cd /homes_unix/hirsch/_goldstd/goldstarResults

/homes_unix/hirsch/_goldstd/goldstarResults


In [21]:
!fslhd /scratch/user/hirsch/goldstd/data_set/t0009/repos01/T1/dmt0009_t1_s02.nii > /homes_unix/hirsch/_goldstd/goldstarResults/imgcalc1.txt
!fslhd /scratch/user/hirsch/datadir/data_results_py/structural/t1_masked_files/struct_image.nii > /homes_unix/hirsch/_goldstd/goldstarResults/imgcalc2.txt

In [22]:
!diff imgcalc1.txt imgcalc2.txt

1c1
< filename       /scratch/user/hirsch/goldstd/data_set/t0009/repos01/T1/dmt0009_t1_s02.nii
---
> filename       /scratch/user/hirsch/datadir/data_results_py/structural/t1_masked_files/struct_image.nii
4c4
< data_type      INT16
---
> data_type      FLOAT64
13,17c13,17
< vox_units      mm
< time_units     s
< datatype       4
< nbyper         2
< bitpix         16
---
> vox_units      Unknown
> time_units     Unknown
> datatype       64
> nbyper         8
> bitpix         64
22,25c22,25
< pixdim4        0.000000
< pixdim5        0.000000
< pixdim6        0.000000
< pixdim7        0.000000
---
> pixdim4        1.000000
> pixdim5        1.000000
> pixdim6        1.000000
> pixdim7        1.000000
29c29
< scl_slope      0.044728
---
> scl_slope      1.000000
46,50c46,50
< qform_name     Aligned Anat
< qform_code     2
< qto_xyz:1      -0.998783  -0.041415  -0.026774  94.499512
< qto_xyz:2      -0.044491  0.990912  0.126939  -140.645218
< qto_xyz:3      -0.021273  -0.127975  0.991549  -

In [40]:
# le header de T1 pour en avoir le coeur net
!fslhd /scratch/user/hirsch/datadir/data_set/t0009/repos01/T1/t0009_t1_s03.nii

Byte swapping
filename       /scratch/user/hirsch/datadir/data_set/t0009/repos01/T1/t0009_t1_s03.nii

sizeof_hdr     348
data_type      INT16
dim0           3
dim1           180
dim2           256
dim3           256
dim4           1
dim5           1
dim6           1
dim7           1
vox_units      mm
time_units     s
datatype       4
nbyper         2
bitpix         16
pixdim0        0.000000
pixdim1        1.000000
pixdim2        1.000000
pixdim3        1.000000
pixdim4        0.000000
pixdim5        0.000000
pixdim6        0.000000
pixdim7        0.000000
vox_offset     352
cal_max        0.0000
cal_min        0.0000
scl_slope      0.185919
scl_inter      0.000000
phase_dim      0
freq_dim       0
slice_dim      0
slice_name     Unknown
slice_code     0
slice_start    0
slice_end      0
slice_duration 0.000000
time_offset    0.000000
intent         Unknown
intent_code    0
intent_name    
intent_p1      0.000000
intent_p2      0.000000
intent_p3      0.000000
qform_name     Aligned An

In [2]:
# le header de l'image calculee pour en avoir le coeur net
!fslhd /scratch/user/hirsch/goldstd/data_set/t0009/repos01/T1/dmt0009_t1_s02.nii

filename       /scratch/user/hirsch/goldstd/data_set/t0009/repos01/T1/dmt0009_t1_s02.nii

sizeof_hdr     348
data_type      INT16
dim0           3
dim1           180
dim2           256
dim3           256
dim4           1
dim5           1
dim6           1
dim7           1
vox_units      mm
time_units     s
datatype       4
nbyper         2
bitpix         16
pixdim0        0.000000
pixdim1        1.000000
pixdim2        1.000000
pixdim3        1.000000
pixdim4        0.000000
pixdim5        0.000000
pixdim6        0.000000
pixdim7        0.000000
vox_offset     352
cal_max        0.0000
cal_min        0.0000
scl_slope      0.044728
scl_inter      0.000000
phase_dim      0
freq_dim       0
slice_dim      0
slice_name     Unknown
slice_code     0
slice_start    0
slice_end      0
slice_duration 0.000000
time_offset    0.000000
intent         Unknown
intent_code    0
intent_name    
intent_p1      0.000000
intent_p2      0.000000
intent_p3      0.000000
qform_name     Aligned Anat
qform_cod

In [12]:
# from SPM we will call image spm_img1
spm_img1_ni = '/scratch/user/hirsch/goldstd/data_set/t0009/repos01/T1/dmt0009_t1_s02.nii'
#print(n1_header['sform_code'])
spm_img1 = nib.load(spm_img1_ni)
spm_img1_header = spm_img1.header
print(spm_img1_header['sform_code'])

2


In [25]:
print(spm_img1_header.get_data_dtype())

int16


In [14]:
spm_img1.affine

array([[ -9.98783350e-01,  -4.14152145e-02,  -2.67708302e-02,
          9.44995117e+01],
       [ -4.44911718e-02,   9.90912259e-01,   1.26938701e-01,
         -1.40645218e+02],
       [ -2.12702751e-02,  -1.27975345e-01,   9.91549253e-01,
         -1.01764404e+02],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.00000000e+00]])

In [16]:
spm_img1.affine.shape

(4, 4)

In [24]:
# from SPM we will call image bias removed T1 image
spm_img0_ni = '/scratch/user/hirsch/goldstd/data_set/t0009/repos01/T1/mt0009_t1_s03.nii'
#print(n1_header['sform_code'])
spm_img0 = nib.load(spm_img0_ni)
spm_img0_header = spm_img0.header
print(spm_img0_header['sform_code'])
print spm_img0.affine
print spm_img0.affine.shape

2
[[ -9.98783350e-01  -4.14152145e-02  -2.67708302e-02   9.44995117e+01]
 [ -4.44911718e-02   9.90912259e-01   1.26938701e-01  -1.40645218e+02]
 [ -2.12702751e-02  -1.27975345e-01   9.91549253e-01  -1.01764404e+02]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
(4, 4)


In [17]:
# from SPM we will call image spm_img1
spm_img2_ni = '/scratch/user/hirsch/datadir/data_results_py/structural/t1_masked_files/struct_image.nii'
#print(n1_header['sform_code'])
spm_img2 = nib.load(spm_img2_ni)
spm_img2_header = spm_img2.header
print(spm_img2_header['sform_code'])
print spm_img2.affine
print spm_img2.affine.shape


2
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
(4, 4)


In [54]:
# le header de l'image calculee pour en avoir le coeur net
!fslhd /scratch/user/hirsch/datadir/data_results_py/structural/t1_masked_files/struct_image.nii

filename       /scratch/user/hirsch/datadir/data_results_py/structural/t1_masked_files/struct_image.nii

sizeof_hdr     348
data_type      FLOAT64
dim0           3
dim1           180
dim2           256
dim3           256
dim4           1
dim5           1
dim6           1
dim7           1
vox_units      Unknown
time_units     Unknown
datatype       64
nbyper         8
bitpix         64
pixdim0        0.000000
pixdim1        1.000000
pixdim2        1.000000
pixdim3        1.000000
pixdim4        1.000000
pixdim5        1.000000
pixdim6        1.000000
pixdim7        1.000000
vox_offset     352
cal_max        0.0000
cal_min        0.0000
scl_slope      1.000000
scl_inter      0.000000
phase_dim      0
freq_dim       0
slice_dim      0
slice_name     Unknown
slice_code     0
slice_start    0
slice_end      0
slice_duration 0.000000
time_offset    0.000000
intent         Unknown
intent_code    0
intent_name    
intent_p1      0.000000
intent_p2      0.000000
intent_p3      0.000000
qform_na

In [13]:
!fslhd  /homes_unix/hirsch/_goldstd/goldstarResults/struct_image.nii

filename       /homes_unix/hirsch/_goldstd/goldstarResults/struct_image.nii

sizeof_hdr     348
data_type      FLOAT64
dim0           3
dim1           180
dim2           256
dim3           256
dim4           1
dim5           1
dim6           1
dim7           1
vox_units      Unknown
time_units     Unknown
datatype       64
nbyper         8
bitpix         64
pixdim0        0.000000
pixdim1        1.000000
pixdim2        1.000000
pixdim3        1.000000
pixdim4        1.000000
pixdim5        1.000000
pixdim6        1.000000
pixdim7        1.000000
vox_offset     352
cal_max        0.0000
cal_min        0.0000
scl_slope      1.000000
scl_inter      0.000000
phase_dim      0
freq_dim       0
slice_dim      0
slice_name     Unknown
slice_code     0
slice_start    0
slice_end      0
slice_duration 0.000000
time_offset    0.000000
intent         Unknown
intent_code    0
intent_name    
intent_p1      0.000000
intent_p2      0.000000
intent_p3      0.000000
qform_name     Unknown
qform_code   

todo etudier la différence entre les 2 images -> aller du coté des headers

## 3 -  Slice timing

In [7]:
!diff   /scratch/user/hirsch/goldstd/data_set/t0009/repos01/EPIBOLD/at0009_epi_s04_d0001.nii   /scratch/user/hirsch/datadir/data_results_py/functionnal/at0009_epi_s04_d0001.nii 

Les fichiers binaires /scratch/user/hirsch/goldstd/data_set/t0009/repos01/EPIBOLD/at0009_epi_s04_d0001.nii et /scratch/user/hirsch/datadir/data_results_py/functionnal/at0009_epi_s04_d0001.nii sont différents


In [8]:
!cmp /scratch/user/hirsch/goldstd/data_set/t0009/repos01/EPIBOLD/at0009_epi_s04_d0001.nii   /scratch/user/hirsch/datadir/data_results_py/functionnal/at0009_epi_s04_d0001.nii 

/scratch/user/hirsch/goldstd/data_set/t0009/repos01/EPIBOLD/at0009_epi_s04_d0001.nii /scratch/user/hirsch/datadir/data_results_py/functionnal/at0009_epi_s04_d0001.nii sont différents: octet 84, ligne 1


Tout d'abord, comparons les headers

In [10]:
!fslhd /scratch/user/hirsch/goldstd/data_set/t0009/repos01/EPIBOLD/at0009_epi_s04_d0001.nii > /homes_unix/hirsch/_goldstd/goldstarResults/h1

In [12]:
!fslhd /scratch/user/hirsch/datadir/data_results_py/functionnal/at0009_epi_s04_d0001.nii > /homes_unix/hirsch/_goldstd/goldstarResults/h2

In [13]:
%cd /homes_unix/hirsch/_goldstd/goldstarResults

/homes_unix/hirsch/_goldstd/goldstarResults


In [14]:
%ls

h1  h2


In [15]:
!diff h1 h2

2c2
< filename       /scratch/user/hirsch/goldstd/data_set/t0009/repos01/EPIBOLD/at0009_epi_s04_d0001.nii
---
> filename       /scratch/user/hirsch/datadir/data_results_py/functionnal/at0009_epi_s04_d0001.nii
20c20
< pixdim1        3.750000
---
> pixdim1        3.749999
49,51c49,51
< qto_xyz:1      -3.742074  -0.174496  -0.170092  123.189674
< qto_xyz:2      -0.181441  3.742512  0.152344  -98.689156
< qto_xyz:3      -0.162663  -0.160252  3.743044  -30.354097
---
> qto_xyz:1      -3.745490  0.078319  -0.166323  116.044998
> qto_xyz:2      0.093387  3.732910  -0.345240  -95.395798
> qto_xyz:3      -0.158354  0.348967  3.730370  -45.065498
58,60c58,60
< sto_xyz:1      -3.742074  -0.174496  -0.170086  123.189674
< sto_xyz:2      -0.181440  3.742512  0.152344  -98.689156
< sto_xyz:3      -0.162658  -0.160252  3.743044  -30.354097
---
> sto_xyz:1      -3.745490  0.078319  -0.166326  116.044998
> sto_xyz:2      0.093387  3.732910  -0.345240  -95.395798
> sto_xyz:3      -0.158358  0.348967  3.

In [33]:
!cat h1

Byte swapping
filename       /scratch/user/hirsch/goldstd/data_set/t0009/repos01/EPIBOLD/at0009_epi_s04_d0001.nii

sizeof_hdr     348
data_type      INT16
dim0           3
dim1           64
dim2           64
dim3           31
dim4           1
dim5           1
dim6           1
dim7           1
vox_units      mm
time_units     s
datatype       4
nbyper         2
bitpix         16
pixdim0        0.000000
pixdim1        3.750000
pixdim2        3.750004
pixdim3        3.750002
pixdim4        0.000000
pixdim5        0.000000
pixdim6        0.000000
pixdim7        0.000000
vox_offset     352
cal_max        0.0000
cal_min        0.0000
scl_slope      1.809520
scl_inter      0.000000
phase_dim      0
freq_dim       0
slice_dim      0
slice_name     Unknown
slice_code     0
slice_start    0
slice_end      0
slice_duration 0.000000
time_offset    0.000000
intent         Unknown
intent_code    0
intent_name    
intent_p1      0.000000
intent_p2      0.000000
intent_p3      0.000000
qform_name     

Maintenant comparons les bitmaps

In [16]:
img1 = '/scratch/user/hirsch/goldstd/data_set/t0009/repos01/EPIBOLD/at0009_epi_s04_d0001.nii'
img2 = '/scratch/user/hirsch/datadir/data_results_py/functionnal/at0009_epi_s04_d0001.nii'

In [ ]:
import numpy as np     
import nibabel as nib     
import os 
    
i1=nib.load(img1)         
i1array=np.asarray(i1.dataobj).copy() # Avoid caching the proxy image
    
i2=nib.load(img2)         
i2array=np.asarray(i2.dataobj).copy()

In [18]:
np.array_equal(i1array, i2array)

True

Slice timing Conclusion: the bitmaps are equal; some differences exist in quaternion and sto

## 4 -  Realignement

pour le gold star, pas de write -> donc pas de comparaison possible...

## 5 -  Coregistration

In [44]:
!diff   /scratch/user/hirsch/goldstd/data_set/t0009/repos01/EPIBOLD/rat0009_epi_s04_d0001.nii   /scratch/user/hirsch/datadir/data_results_py/functionnal/crat0009_epi_s04_d0001.nii

Les fichiers binaires /scratch/user/hirsch/goldstd/data_set/t0009/repos01/EPIBOLD/rat0009_epi_s04_d0001.nii et /scratch/user/hirsch/datadir/data_results_py/functionnal/crat0009_epi_s04_d0001.nii sont différents


comparons les headers

In [45]:
!fslhd /scratch/user/hirsch/goldstd/data_set/t0009/repos01/EPIBOLD/rat0009_epi_s04_d0001.nii > /homes_unix/hirsch/_goldstd/goldstarResults/coreg1.txt
!fslhd /scratch/user/hirsch/datadir/data_results_py/functionnal/crat0009_epi_s04_d0001.nii > /homes_unix/hirsch/_goldstd/goldstarResults/coreg2.txt

In [46]:
!diff coreg1.txt coreg2.txt

2c2
< filename       /scratch/user/hirsch/goldstd/data_set/t0009/repos01/EPIBOLD/rat0009_epi_s04_d0001.nii
---
> filename       /scratch/user/hirsch/datadir/data_results_py/functionnal/crat0009_epi_s04_d0001.nii


les headers sont les mêmes
Allons voir les bit maps

In [47]:
img1 = '/scratch/user/hirsch/goldstd/data_set/t0009/repos01/EPIBOLD/rat0009_epi_s04_d0001.nii'
img2 = '/scratch/user/hirsch/datadir/data_results_py/functionnal/crat0009_epi_s04_d0001.nii'

In [48]:
i1=nib.load(img1)         
i1array=np.asarray(i1.dataobj).copy() # Avoid caching the proxy image
    
i2=nib.load(img2)         
i2array=np.asarray(i2.dataobj).copy()

In [49]:
np.array_equal(i1array, i2array)

False

In [53]:
np.allclose(i1array, i2array, rtol=1e-02)

False

In [32]:
!fslview /scratch/user/hirsch/goldstd/data_set/t0009/repos01/EPIBOLD/rat0009_epi_s04_d0001.nii

In [31]:
!mricron /scratch/user/hirsch/goldstd/data_set/t0009/repos01/EPIBOLD/rat0009_epi_s04_d0001.nii

[WARNING] Out of OEM specific VK codes, changing to unassigned
[WARNING] Out of unassigned VK codes, assigning $FF
^C


# Annexes

In [35]:
## batch SPM12

In [34]:
!cat /homes_unix/hirsch/_goldstd/all_process_v9_thomas_goldstd.m

%-----------------------------------------------------------------------
% Job saved on 17-Mar-2017 14:00:36 by cfg_util (rev $Rev: 6460 $)
% spm SPM - SPM12 (6906)
% cfg_basicio BasicIO - Unknown
%-----------------------------------------------------------------------
matlabbatch{1}.spm.spatial.preproc.channel.vols = {'/scratch/user/hirsch/goldstd/data_set/t0009/repos01/T1/t0009_t1_s03.nii,1'};
matlabbatch{1}.spm.spatial.preproc.channel.biasreg = 0.001;
matlabbatch{1}.spm.spatial.preproc.channel.biasfwhm = 60;
matlabbatch{1}.spm.spatial.preproc.channel.write = [1 1];
matlabbatch{1}.spm.spatial.preproc.tissue(1).tpm = {'/srv/shares/softs/spm12-full/tpm/TPM.nii,1'};
matlabbatch{1}.spm.spatial.preproc.tissue(1).ngaus = 1;
matlabbatch{1}.spm.spatial.preproc.tissue(1).native = [1 0];
matlabbatch{1}.spm.spatial.preproc.tissue(1).warped = [0 0];
matlabbatch{1}.spm.spatial.preproc.tissue(2).tpm = {'/srv/shares/softs/spm12-full/tpm/TPM.nii,2'};
matlabbatch{1}.spm.spatial.preproc.tissue(2).ngau