v1 à V2 -> on va deja voir si on prend un voxel dans la région 1 comme seed, ca marche sur les voxels dela region 1

In [1]:
import os

import numpy as np
import matplotlib.pyplot as plt
import nibabel as nib

In [2]:
from pydoc import help
from scipy.stats.stats import pearsonr
help(pearsonr)

Help on function pearsonr in module scipy.stats.stats:

pearsonr(x, y)
    Calculates a Pearson correlation coefficient and the p-value for testing
    non-correlation.
    
    The Pearson correlation coefficient measures the linear relationship
    between two datasets. Strictly speaking, Pearson's correlation requires
    that each dataset be normally distributed, and not necessarily zero-mean.
    Like other correlation coefficients, this one varies between -1 and +1
    with 0 implying no correlation. Correlations of -1 or +1 imply an exact
    linear relationship. Positive correlations imply that as x increases, so
    does y. Negative correlations imply that as x increases, y decreases.
    
    The p-value roughly indicates the probability of an uncorrelated system
    producing datasets that have a Pearson correlation at least as extreme
    as the one computed from these datasets. The p-values are not entirely
    reliable but are probably reasonable for datasets larger than 

In [3]:
regSeedFile = '/homes_unix/hirsch/_ipnotebooks/region_image.nii'
reg_data=nib.load(regSeedFile) 
regarray=np.asarray(reg_data.dataobj)
# transpose(nonzero(a))
reg1_coords = np.transpose(np.nonzero(regarray))
volume_shape = reg1_coords.shape
print volume_shape
coords = list(np.ndindex(volume_shape))
print len(coords)

(1289, 3)
3867
(1289, 3)
3867


In [21]:
volume_shape[0], reg1_coords[0], coords

(1289,
 array([62, 77, 29]),
 [(0, 0),
  (0, 1),
  (0, 2),
  (1, 0),
  (1, 1),
  (1, 2),
  (2, 0),
  (2, 1),
  (2, 2),
  (3, 0),
  (3, 1),
  (3, 2),
  (4, 0),
  (4, 1),
  (4, 2),
  (5, 0),
  (5, 1),
  (5, 2),
  (6, 0),
  (6, 1),
  (6, 2),
  (7, 0),
  (7, 1),
  (7, 2),
  (8, 0),
  (8, 1),
  (8, 2),
  (9, 0),
  (9, 1),
  (9, 2),
  (10, 0),
  (10, 1),
  (10, 2),
  (11, 0),
  (11, 1),
  (11, 2),
  (12, 0),
  (12, 1),
  (12, 2),
  (13, 0),
  (13, 1),
  (13, 2),
  (14, 0),
  (14, 1),
  (14, 2),
  (15, 0),
  (15, 1),
  (15, 2),
  (16, 0),
  (16, 1),
  (16, 2),
  (17, 0),
  (17, 1),
  (17, 2),
  (18, 0),
  (18, 1),
  (18, 2),
  (19, 0),
  (19, 1),
  (19, 2),
  (20, 0),
  (20, 1),
  (20, 2),
  (21, 0),
  (21, 1),
  (21, 2),
  (22, 0),
  (22, 1),
  (22, 2),
  (23, 0),
  (23, 1),
  (23, 2),
  (24, 0),
  (24, 1),
  (24, 2),
  (25, 0),
  (25, 1),
  (25, 2),
  (26, 0),
  (26, 1),
  (26, 2),
  (27, 0),
  (27, 1),
  (27, 2),
  (28, 0),
  (28, 1),
  (28, 2),
  (29, 0),
  (29, 1),
  (29, 2),
  (30, 0),


(1289,
 array([62, 77, 29]),
 [(0, 0),
  (0, 1),
  (0, 2),
  (1, 0),
  (1, 1),
  (1, 2),
  (2, 0),
  (2, 1),
  (2, 2),
  (3, 0),
  (3, 1),
  (3, 2),
  (4, 0),
  (4, 1),
  (4, 2),
  (5, 0),
  (5, 1),
  (5, 2),
  (6, 0),
  (6, 1),
  (6, 2),
  (7, 0),
  (7, 1),
  (7, 2),
  (8, 0),
  (8, 1),
  (8, 2),
  (9, 0),
  (9, 1),
  (9, 2),
  (10, 0),
  (10, 1),
  (10, 2),
  (11, 0),
  (11, 1),
  (11, 2),
  (12, 0),
  (12, 1),
  (12, 2),
  (13, 0),
  (13, 1),
  (13, 2),
  (14, 0),
  (14, 1),
  (14, 2),
  (15, 0),
  (15, 1),
  (15, 2),
  (16, 0),
  (16, 1),
  (16, 2),
  (17, 0),
  (17, 1),
  (17, 2),
  (18, 0),
  (18, 1),
  (18, 2),
  (19, 0),
  (19, 1),
  (19, 2),
  (20, 0),
  (20, 1),
  (20, 2),
  (21, 0),
  (21, 1),
  (21, 2),
  (22, 0),
  (22, 1),
  (22, 2),
  (23, 0),
  (23, 1),
  (23, 2),
  (24, 0),
  (24, 1),
  (24, 2),
  (25, 0),
  (25, 1),
  (25, 2),
  (26, 0),
  (26, 1),
  (26, 2),
  (27, 0),
  (27, 1),
  (27, 2),
  (28, 0),
  (28, 1),
  (28, 2),
  (29, 0),
  (29, 1),
  (29, 2),
  (30, 0),


In [6]:
fmri_file = '/scratch/user/hirsch/datadir4/data_results_py/functionnal/arima/arimaResidus/_report/arima_residu.nii.gz'
fmri_data=nib.load(fmri_file) 
fmri_array=np.asarray(fmri_data.dataobj)


In [4]:
reg1_coords[600]

array([70, 71, 46])

array([70, 71, 46])

In [5]:
n_targets = 10

# Choose n_targets random voxels to be the target voxels
targets = np.random.randint(0, len(reg1_coords), n_targets)
coords_targets = np.array(reg1_coords)[targets]
print coords_targets
print coords_targets.shape

[[69 75 36]
 [71 79 38]
 [68 74 36]
 [73 71 49]
 [71 81 34]
 [70 72 43]
 [74 70 41]
 [72 69 45]
 [71 84 35]
 [71 76 37]]
(10, 3)
[[69 75 36]
 [71 79 38]
 [68 74 36]
 [73 71 49]
 [71 81 34]
 [70 72 43]
 [74 70 41]
 [72 69 45]
 [71 84 35]
 [71 76 37]]
(10, 3)


In [13]:
# seed_ts_array
seed_ts_array = fmri_array[70, 71, 46, :]

In [22]:
seed_ts_array

array([ -6.61161903e-05,  -1.69608605e+00,   1.50383914e+00,
         1.46056938e+00,   5.26908934e-01,  -1.05196035e+00,
        -1.21814048e+00,  -6.18498623e-01,   4.84663785e-01,
         9.33310091e-01,   1.06962955e+00,   6.25676632e-01,
        -4.32228670e-02,  -1.15094697e+00,  -1.74416375e+00,
        -1.28833187e+00,   5.10264635e-01,   2.24197817e+00,
         2.55062056e+00,   7.71695375e-01,  -1.67422163e+00,
        -2.98712301e+00,  -2.00991559e+00,   3.25098723e-01,
         2.31255174e+00,   2.40586448e+00,   7.92863548e-01,
        -1.29217386e+00,  -2.13237953e+00,  -1.20037198e+00,
         7.92846859e-01,   2.01030588e+00,   1.35199130e+00,
        -7.95128107e-01,  -2.33548427e+00,  -1.72938466e+00,
         7.13855922e-01,   2.51235008e+00,   1.87035549e+00,
        -6.82238281e-01,  -2.23667717e+00,  -9.84779894e-01,
         1.94114065e+00,   3.15344119e+00,   9.91942883e-01,
        -2.63740182e+00,  -3.89883995e+00,  -1.42567778e+00,
         2.18982196e+00,

array([ -6.61161903e-05,  -1.69608605e+00,   1.50383914e+00,
         1.46056938e+00,   5.26908934e-01,  -1.05196035e+00,
        -1.21814048e+00,  -6.18498623e-01,   4.84663785e-01,
         9.33310091e-01,   1.06962955e+00,   6.25676632e-01,
        -4.32228670e-02,  -1.15094697e+00,  -1.74416375e+00,
        -1.28833187e+00,   5.10264635e-01,   2.24197817e+00,
         2.55062056e+00,   7.71695375e-01,  -1.67422163e+00,
        -2.98712301e+00,  -2.00991559e+00,   3.25098723e-01,
         2.31255174e+00,   2.40586448e+00,   7.92863548e-01,
        -1.29217386e+00,  -2.13237953e+00,  -1.20037198e+00,
         7.92846859e-01,   2.01030588e+00,   1.35199130e+00,
        -7.95128107e-01,  -2.33548427e+00,  -1.72938466e+00,
         7.13855922e-01,   2.51235008e+00,   1.87035549e+00,
        -6.82238281e-01,  -2.23667717e+00,  -9.84779894e-01,
         1.94114065e+00,   3.15344119e+00,   9.91942883e-01,
        -2.63740182e+00,  -3.89883995e+00,  -1.42567778e+00,
         2.18982196e+00,

In [23]:
# np.full(shape, fill_value, dtype=None, order='C')

corr_matrix = np.full(reg_data.shape, 0, dtype=float)

In [27]:
for i in range(reg1_coords.shape[0]):
    target_array = fmri_array[reg1_coords[i, 0], reg1_coords[i, 1],reg1_coords[i,2], :]
    #print target_array
    non_zero_nb = np.count_nonzero(target_array)
    if non_zero_nb:
        try:
            p = pearsonr(seed_ts_array,target_array) 
            if p[0] > 0.5:
                print p[0]
            corr_matrix[reg1_coords[i, 0], reg1_coords[i, 1],reg1_coords[i,2]] = p[0] 
        except:
            print "exception"
    
# save matrix in a file
# create the resulting image
corr_image = nib.Nifti1Image(corr_matrix,affine=reg_data.affine, header=reg_data.header)
# save the correlation array
out_file = os.getcwd() + '/' + 'corr_reg1v2.nii'
nib.save(corr_image, out_file)
    

0.519092
0.527915
0.556794
0.708765
0.659926
0.502853
0.556471
0.523136
0.557987
0.502971
0.503845
0.581558
0.719349
0.895676
0.851765
0.725691
0.900906
0.739868
0.535759
0.576853
0.542197
0.568796
0.526576
0.572024
0.597589
0.560826
0.543679
0.756671
0.893392
0.876062
0.526839
0.922791
1.0
0.820287
0.748973
0.824732
0.557499
0.5348770.519092
0.527915
0.556794
0.708765
0.659926
0.502853
0.556471
0.523136
0.557987
0.502971
0.503845
0.581558
0.719349
0.895676
0.851765
0.725691
0.900906
0.739868
0.535759
0.576853
0.542197
0.568796
0.526576
0.572024
0.597589
0.560826
0.543679
0.756671
0.893392
0.876062
0.526839
0.922791
1.0
0.820287
0.748973
0.824732
0.557499
0.534877
0.574555
0.655223
0.790361
0.75604
0.818022
0.869628
0.731304
0.66694
0.72106
0.511754
0.535825
0.527912
0.53231
0.545795
0.5235
0.529308
0.500025
0.532228
0.500083
0.551215
0.518668
0.539666
0.547423
0.534825
0.545882
0.576781
0.583289

0.574555
0.655223
0.790361
0.75604
0.818022
0.869628
0.731304
0.66694
0.72106
0.511754
0.

In [ ]:
thresh = 0.2


In [ ]:
coords_targets.shape[1]


In [ ]:
n_targets = 100

# Choose n_targets random voxels to be the target voxels
targets = np.random.randint(0, len(coords), n_targets)
coords_targets = np.array(coords)[targets].T
print coords_targets
print coords_targets.shape

In [ ]:
iarray[71,63, 22, :].shape

In [ ]:
coords_targets[0,0], coords_targets[1,0],coords_targets[2,0]

In [ ]:
[coords_targets[0,i], coords_targets[1,i],coords_targets[2,i]]

In [ ]:
for i in range(n_targets):
    target_array = iarray[coords_targets[0,i], coords_targets[1,i],coords_targets[2,i], :]
    #print target_array
    non_zero_nb = np.count_nonzero(target_array)
    print "nbs"
    print non_zero_nb
    #print target_array.shape
    p = pearsonr(seed_ts_array,target_array) 
    print p

In [ ]:
# on va calculer la correlation de peason pour ces 100 targets

i = 0
target_array = iarray[coords_targets[0,i], coords_targets[1,i],coords_targets[2,i], :]
#print target_array
non_zero_nb = np.count_nonzero(target_array)
print "nbs"
print non_zero_nb
print target_array.shape
p = pearsonr(seed_ts_array,target_array) 
print p

In [ ]:
target_array

# fin code nouveau 

In [ ]:
# Make the seed time series:
time_series_seed = io.time_series_from_file(fmri_file,
                                coords_seeds,
                                TR=TR,
                                normalize='percent',
                                filter=dict(lb=f_lb,
                                            ub=f_ub,
                                            method='boxcar'))

# Make the target time series:
time_series_target = io.time_series_from_file(fmri_file,
                                          coords_target,
                                          TR=TR,
                                          normalize='percent',
                                          filter=dict(lb=f_lb,
                                                      ub=f_ub,
                                                    method='boxcar'))

In [ ]:
A = nta.SeedCoherenceAnalyzer(time_series_seed, time_series_target,
                            method=dict(NFFT=20))
B = nta.SeedCorrelationAnalyzer(time_series_seed, time_series_target)

In [ ]:
freq_idx = np.where((A.frequencies > f_lb) * (A.frequencies < f_ub))[0]

In [ ]:
cor = []
coh = []

for this_seed in range(n_seeds):
    # Extract the coherence and average across these frequency bands:
    coh.append(np.mean(A.coherence[this_seed][:, freq_idx], -1))  # Averaging on the
                                                                 # last dimension

    cor.append(B.corrcoef[this_seed])  # No need to do any additional
                                       # computation

In [ ]:
coh